### ISSUE TITLE
Set NoDelay = true by default 

### ISSUE THREAD

**Issue by sancheolz** [ImoutoChan/websocket-sharp-core#9]
In Linux TCP socket used NoDelay = false by default. This means that socket will wait until send buffer filled to send it's content. As result short messages will delivered much later from moment they putted to buffer. Could you set NoDelay = true by default?

**Comment by ImoutoChan** [comment]
Hi!

This project has no tests, so I can't realistically make any changes without potentially breaking existing functionality and scenarios. Right now I'm not interested in developing tests either, since the original intention was to just mirror-copy everything to net standard.

In the meantime, both this fork and the original library are written under the MIT license, so feel free to fork it again or copy its content into your project.

**Comment by sancheolz** [comment]
This is a small change that will add access to the NoDelay field from TcpClient. The code has already been tested on my tests and significantly speeds up data transfer on Linux. I am doing PR because the CoreRemoting project uses the nuget package of this project and I would like to see this package with a fix on nuget.org because creating my own nuget package and putting it on nuget.org looks difficult for me right now.
